export const beamsData = [
  {
    id: 1,
    status: "added",
    beamNo: "BM-001",
    beamDate: "2025-02-01",
    partyName: "Self Product",
    isOutsourcing: false,
    yarnQuality: "SuperSoft 30D",
    machineNo: "MC001",
    lotNo: "LOT-1001",
    beamLength: 1200,
    remainingMeter: 1150,
    remainingPercentage: "95.8%",
    daysToFinish: 3,
    pannaNo: "PANNA-ALP-001",
    danier: "30D",
    totalEnds: 5000,
    pipeNumber: "P-12",
    startSerialTaka: 1500,
    endSerialTaka: 2000,
    totalFoldingTaka: 12000,
    totalFoldingMeter: 1180,
    krills: 12,
    section: "A",
    beamGetter: "Rajesh Kumar",
  },
  {
    id: 2,
    status: "running",
    beamNo: "BM-002",
    beamDate: "2025-02-05",
    partyName: "Omega Fabrics LLP",
    isOutsourcing: true,
    yarnQuality: "PrimeWeft 25D",
    machineNo: "MC002",
    lotNo: "LOT-1002",
    beamLength: 980,
    remainingMeter: 650,
    remainingPercentage: "66.3%",
    daysToFinish: 2,
    pannaNo: "PANNA-OMG-002",
    danier: "25D",
    totalEnds: 4200,
    pipeNumber: "P-08",
    startSerialTaka: 1200,
    endSerialTaka: 1800,
    totalFoldingTaka: 9500,
    totalFoldingMeter: 950,
    krills: 10,
    section: "B",
    beamGetter: "Amit Patel",
  },
  {
    id: 3,
    status: "released",
    beamNo: "BM-003",
    beamDate: "2025-01-25",
    partyName: "Self Product",
    isOutsourcing: false,
    yarnQuality: "ComfortWeave 40D",
    machineNo: "MC003",
    lotNo: "LOT-0999",
    beamLength: 1050,
    remainingMeter: 0,
    remainingPercentage: "0%",
    daysToFinish: 0,
    pannaNo: "PANNA-ALP-003",
    danier: "40D",
    totalEnds: 4800,
    pipeNumber: "P-10",
    startSerialTaka: 1400,
    endSerialTaka: 1900,
    totalFoldingTaka: 11200,
    totalFoldingMeter: 1045,
    krills: 11,
    section: "C",
  },
];