export const yarnData = [
  // Alpha Textiles Pvt Ltd (firmId: 1)
  {
    id: 101,
    firmId: 1,
    challanDate: "2025-01-10",
    challanNo: "CH-ALP-001",
    receiveDate: "2025-01-11",
    time: "10:30",
    fromFirm: "Alpha Textiles Pvt Ltd",
    agentName: "Rohit Mehta",
    manufacture: "Shree Spinners",
    danier: "30D",
    yarnFillment: "Full",
    qualityName: "SuperSoft",
    grade: "A",
    yarnType: "Polyester",
    lrNo: "LR-99812",
    cartoonNo: "CT-001",
    totalCartoon: 20,
    totalCone: 600,
    netWeight: 520.5,
    truckNo: "GJ-05-AB-1123",
  },
  {
    id: 102,
    firmId: 1,
    challanDate: "2025-01-15",
    challanNo: "CH-ALP-002",
    receiveDate: "2025-01-16",
    time: "15:45",
    fromFirm: "Alpha Textiles Pvt Ltd",
    agentName: "Neha Shah",
    manufacture: "Vraj Spinners",
    danier: "40D",
    yarnFillment: "Partial",
    qualityName: "ComfortWeave",
    grade: "B",
    yarnType: "Nylon",
    lrNo: "LR-99845",
    cartoonNo: "CT-002",
    totalCartoon: 12,
    totalCone: 360,
    netWeight: 310.0,
    truckNo: "GJ-05-CD-3344",
  },

  // Omega Fabrics LLP (firmId: 2)
  {
    id: 201,
    firmId: 2,
    challanDate: "2025-02-03",
    challanNo: "CH-OMG-001",
    receiveDate: "2025-02-04",
    time: "09:20",
    fromFirm: "Omega Fabrics LLP",
    agentName: "Imran Khan",
    manufacture: "Neel Spinners",
    danier: "20D",
    yarnFillment: "Full",
    qualityName: "PrimeWeft",
    grade: "A",
    yarnType: "Cotton",
    lrNo: "LR-10012",
    cartoonNo: "CT-101",
    totalCartoon: 25,
    totalCone: 750,
    netWeight: 615.8,
    truckNo: "MH-01-EF-7788",
  },
  {
    id: 202,
    firmId: 2,
    challanDate: "2025-02-10",
    challanNo: "CH-OMG-002",
    receiveDate: "2025-02-11",
    time: "13:05",
    fromFirm: "Omega Fabrics LLP",
    agentName: "Saloni Patel",
    manufacture: "Sagar Spinners",
    danier: "25D",
    yarnFillment: "Partial",
    qualityName: "Durastretch",
    grade: "B",
    yarnType: "Viscose",
    lrNo: "LR-10036",
    cartoonNo: "CT-102",
    totalCartoon: 10,
    totalCone: 300,
    netWeight: 245.2,
    truckNo: "MH-02-GH-5599",
  },
];